const Intro =
  "For this project, I worked on a \"Branding package\", creating a logo, branding, and website prototype for a new restaurant called CaribFood. I chose the name CaribFood because it's short and easy to remember. The tagline, 'Discover the Caribbean flavour', and the bright colours match the idea of tropical elegance.";
const Tools = ["Adobe Illustrator", "Adobe Photoshop", "Adobe XD"];
const Content = [
  // {
  //   article_header: "",
  //   article_leading_content: [
  //     "When presenting these options to the owner of Green Thermique, it became evident that logo variation 1 stood out as the most fitting choice.",
  //   ],
  //   article_figures: [
  //     {
  //       link: "javascript:void(0)",
  //       img: "/images/greenthermique/LOGO1@4x.png",
  //       alt: "Greenthermique logo 1",
  //       caption: "Gradient Logo<br>Click for more details",
  //       captionList: [
  //         "Gradient colours offer a modern and dynamic look, add depth and dimension, reflect a unique brand personality, emphasize visual interest, and enhance the overall user experience on digital platforms.",
  //       ],
  //       title: "",
  //       text: "",
  //       modal_id: "gtv1",
  //       isModal: true,
  //     },
  //     {
  //       link: "javascript:void(0)",
  //       img: "/images/greenthermique/GT SOLID@4x.png",
  //       alt: "Greenthermique logo 2",
  //       caption: "Solid logo<br>Click for more details",
  //       captionList: [
  //         "Solid colours are often associated with timelessness and simplicity. They add scalability, versatility, visibility  across mediums. Overall they convey a sense of readability and set an easy and memorable brand recognition overtime.",
  //       ],
  //       title: "",
  //       text: "",
  //       modal_id: "gtv2",
  //       isModal: true,
  //     },
  //   ],
  //   subtitle: "Logo style frame",
  //   hasTitle: false,
  //   hasSubtitle: true,
  //   hasFigure: true,
  //   article_content:
  //     "Green Thermique decision to choose the gradient logo over the solid version was driven by their desire to create a brand identity that not only reflects their values and aspirations but also resonates deeply with their audience. With its modern look, depth, and visual interest, the gradient logo embodies the spirit of innovation and sustainability that defines Green Thermique. Ultimately, the business opted for the Logo1 (Gradient logo) design and animation as it best aligns with their brand identity.",
  //   isContentList: false,
  //   isNumberedList: false,
  //   hasMoreImages: false,
  //   article_img_caption: "Style frame by CatGy",
  // },
  {
    article_header: "Ideation",
    article_image: "/images/caribfood/caribfood_4.png",
    article_img_alt: "Article image",
    article_leading_content: [
      "To get the right look and feel, I made two mood-boards: one called 'Frenzy' and the other 'Chic.' I used words like fresh, tasty, vibrant, and friendly to guide my design choices. The colours I picked—yellow and green—show the liveliness of the Caribbean.",
    ],
    article_figures: [
      {
        link: "javascript:void(0)",
        img: "/images/caribfood/Logo1@4x.png",
        alt: "Caribfood logo 1",
        caption: "Filled Logo<br>Click for more details",
        captionList: [
          "'Gradient colours offer a modern and dynamic look, add depth and dimension, reflect a unique brand personality, emphasize visual interest, and enhance the overall user experience on digital platforms.'",
        ],
        title: "",
        text: "",
        modal_id: "gtv1",
        isModal: true,
      },
      {
        link: "javascript:void(0)",
        img: "/images/caribfood/Logo2@4x.png",
        alt: "Caribfood logo 2",
        caption: "Outlined logo<br>Click for more details",
        captionList: [
          "'Solid colours are often associated with timelessness and simplicity. They add scalability, versatility, visibility  across mediums. Overall they convey a sense of readability and set an easy and memorable brand recognition overtime.'",
        ],
        title: "",
        text: "",
        modal_id: "gtv2",
        isModal: true,
      },
    ],
    subtitle: "Logo",
    hasTitle: true,
    hasSubtitle: true,
    hasFigure: true,
    article_content: "",
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "CaribFood logo by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/Branding.png",
    article_img_alt: "Article image",
    article_leading_content: [
      "Typography was really important. We picked clean and modern fonts like Bodoni 72 and Helvetica Light for their readability and contemporary appeal. The design has curved shapes and sleek lines to make it feel warm and stylish.",
    ],
    subtitle: "Branding materials",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Storyboard by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    extraImages: [
      {
        link: "javascript:void(0)",
        img: "/images/caribfood/caribfood_5.jpg",
        alt: "portfolio image 1",
        caption: "Tools: Adobe Illustrator",
        captionList: [
          "'Solid colours are often associated with timelessness and simplicity. They add scalability, versatility, visibility  across mediums. Overall they convey a sense of readability and set an easy and memorable brand recognition overtime.'",
        ],
        title: "",
        text: "",
        modal_id: "cb1",
        isModal: true,
      },
      {
        link: "javascript:void(0)",
        img: "/images/caribfood/caribfood_6.jpg",
        alt: "portfolio image 1",
        caption: "Tools: Adobe Illustrator",
        captionList: [
          "'Solid colours are often associated with timelessness and simplicity. They add scalability, versatility, visibility  across mediums. Overall they convey a sense of readability and set an easy and memorable brand recognition overtime.'",
        ],
        title: "",
        text: "",
        modal_id: "cb2",
        isModal: true,
      },
    ],
    article_content: [
      "Letterhead: The letterhead maintains the colour scheme and presents a professional and cohesive appearance, ideal for official documents and correspondence",
      "Envelope: The standard envelope reflects the branding elements, featuring a harmonious colour scheme that embodies the essence of the restaurant's identity.",
    ],
    isContentList: true,
    isNumberedList: false,
    hasMoreImages: true,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "CaribFood targets a diverse demographic, including families, friends, and culinary enthusiasts eager to explore Caribbean cuisine. This diversity was reflected in the user testing phase, where a varied group of users, including peers, friends, and family, engaged with the prototype website, to make sure it's easy to use.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "The branding collateral for this project includes the following essential items:",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    article_figures: [
      {
        link: "javascript:void(0)",
        img: "/images/caribfood/businesscard1.jpg",
        alt: "Business card 1",
        caption: "Business card 1<br>Click for more details",
        captionList: [
          "'Gradient colours offer a modern and dynamic look, add depth and dimension, reflect a unique brand personality, emphasize visual interest, and enhance the overall user experience on digital platforms.'",
        ],
        title: "",
        text: "",
        modal_id: "cbbc1",
        isModal: true,
      },
      {
        link: "javascript:void(0)",
        img: "/images/caribfood/businesscard2.jpg",
        alt: "Business card 2",
        caption: "Business card 2<br>Click for more details",
        captionList: [
          "'Solid colours are often associated with timelessness and simplicity. They add scalability, versatility, visibility  across mediums. Overall they convey a sense of readability and set an easy and memorable brand recognition overtime.'",
        ],
        title: "",
        text: "",
        modal_id: "cbbc2",
        isModal: true,
      },
      {
        link: "javascript:void(0)",
        img: "/images/caribfood/businesscard3.jpg",
        alt: "Business card 3",
        caption: "Business card 3<br>Click for more details",
        captionList: [
          "'Solid colours are often associated with timelessness and simplicity. They add scalability, versatility, visibility  across mediums. Overall they convey a sense of readability and set an easy and memorable brand recognition overtime.'",
        ],
        title: "",
        text: "",
        modal_id: "cbbc3",
        isModal: true,
      },
      {
        link: "javascript:void(0)",
        img: "/images/caribfood/businesscard4.jpg",
        alt: "Business card 4",
        caption: "Business card 4<br>Click for more details",
        captionList: [
          "'Solid colours are often associated with timelessness and simplicity. They add scalability, versatility, visibility  across mediums. Overall they convey a sense of readability and set an easy and memorable brand recognition overtime.'",
        ],
        title: "",
        text: "",
        modal_id: "cbbc4",
        isModal: true,
      },
    ],
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: true,
    article_content: [
      "Business card: The business card showcases the logo along with the restaurant's contact information and a barcode, all while maintaining a sleek and modern aesthetic. ",
    ],
    isContentList: true,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Together, these collateral pieces contribute to a consistent and memorable brand image for CaribFood Restaurant Prototype.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    article_leading_content: [
      "For the CaribFood prototype, I started by drawing basic layout and structure of the application across different screen sizes, focusing on key functionalities such as menu browsing, ordering, and checkout.",
    ],
    article_figures: [
      {
        link: "javascript:void(0)",
        img: "/images/caribfood/caribfood_7.png",
        alt: "Business card 1",
        caption: "Business card 1<br>Click for more details",
        captionList: [
          "'Gradient colours offer a modern and dynamic look, add depth and dimension, reflect a unique brand personality, emphasize visual interest, and enhance the overall user experience on digital platforms.'",
        ],
        title: "",
        text: "",
        modal_id: "cbfidelity1",
        isModal: true,
        fullScreen: true,
      },
    ],
    subtitle: "Wireframe to high fidelity prototypes",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: true,

    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "I then progressively developed low and mid-fidelity designs by introduced more detailed visual elements, including colour schemes, typography, and imagery, to enhance the user experience further. The mobile version prioritized streamlined navigation and intuitive touch controls, while the tablet and desktop versions showcased rich visuals and enhance user engagement.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "User Testing",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "To assess the user experience of CaribFood's prototype and ensure it matches the brand's identity while catering to a diverse audience, we conducted the following user testing:We invited a varied group, including peers, friends, family members, and food enthusiasts, to interact with the UI/UX prototype of the CaribFood website. Participants were asked to place an order for a complete meal, consisting of a Creole Bliss meal and a Carib Smoothie, and proceed to payment to obtain a receipt via this link:",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
    hasLink: true,
    link_name: "CaribFood Restaurant",
    article_link_text: "CaribFood Restaurant",
    article_link:
      "https://xd.adobe.com/view/80c1462a-d598-4cb6-b291-544383abd601-d592/",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "The testing scenario assumed participants had already created an account or used an authentication method (such as Google) to sign up. They were then prompted to follow the provided scenario for placing their order.We assessed various metrics during the testing process:",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Exploration and Navigation: Participants were instructed to explore different sections of the website or app to find information about the restaurant, menu offerings, and contact details.",
      "Placing an Order: Participants were asked to simulate the process of ordering a meal through the prototype to evaluate the ease of use and clarity of the ordering system.",
      "Finding Information: Participants were tasked with locating specific information, such as the restaurant's address, operating hours, and detailed menu options, including vegetarian or gluten-free choices.",
      "Contact and Support: Participants were requested to locate the contact information and simulate sending a query or feedback to assess the accessibility of customer support.",
    ],
    isContentList: true,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Feedback was collected to evaluate navigation, ordering, information retrieval, and support features. Metrics such as task success, time-on-task, satisfaction, accessibility, design aesthetics, and responsiveness were measured.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "Final Ouput",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Overall, the goal of this user testing was to refine the platform, ensuring it offers a user-friendly and visually appealing experience that captures the essence of the Caribbean spirit while meeting the diverse needs of its users.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
];

export default { Content, Intro, Tools };
