const Intro =
  "The objective of this project was to develop an augmented reality (AR) experience for CatGy Furn, offering users a virtual shopping experience accessible to those unable to visit a physical store. The project commenced with the creation of 3D furniture pieces using Adobe 3D Stager, followed by the development of an AR experience in Adobe Aero triggered by a QR code. This innovative concept mirrors the in-person shopping experience and leverages AR technology to provide users with a unique and engaging shopping journey.";
const Tools = ["Adobe 3D Stager", "Adobe Illustrator", "Adobe Aero Beta"];
const Content = [
  {
    article_header: "Ideation",
    article_image: "",
    article_img_alt: "",
    subtitle: "Research and Inspiration",
    hasTitle: true,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "Research was conducted to understand the potential of AR technology in the realm of virtual shopping and marketing. This involved studying existing AR applications and experiences, particularly those related to furniture shopping. Inspiration was drawn from successful AR implementations and innovative marketing campaigns.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: false,
    link_name: "Image by starline",
  },
  {
    article_header: "",
    article_image: "/images/pawpatrol/storyboard.png",
    article_img_alt: "Article image",
    subtitle: "Design and Development",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "With the tools and technologies identified, the design and development process began. This involved creating 3D models of the furniture pieces using Adobe 3D Stager, selecting a colour palette to convey the desired aesthetic, and importing the models into Adobe Aero to build the AR experience.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Storyboard by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/pawpatrol/merchandise.png",
    article_img_alt: "Article image",
    subtitle: "Storyboard and Script",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "Ideation began with the drafting of a storyboard and script, outlining the key features and functionalities of the AR experience. The goal was to create a seamless and immersive shopping experience for users, allowing them to visualize and manipulate furniture pieces in their own space.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/pawpatrol/merchandise.png",
    article_img_alt: "Article image",
    subtitle: "Preparation material",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "Using Adobe 3D Stager, I crafted 3D furniture pieces, selecting a colour palette consisting of brown, tan, burgundy, olive green, and beige to convey modernity and quality. These 3D models were then imported into Adobe Aero to create the AR installation triggered by a QR code.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/pawpatrol/merchandise.png",
    article_img_alt: "Article image",
    subtitle: "Shots/ Screens for the interview",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "Screenshots or video clips demonstrating the AR experience in Adobe Aero, showcasing the furniture pieces in various color options and styles.Visuals of the QR code used to trigger the AR installation, providing users with easy access to the virtual shopping experience.User interface (UI) screens from the AR app, displaying options for browsing furniture, selecting items, and customizing their appearance in real-time.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/pawpatrol/merchandise.png",
    article_img_alt: "Article image",
    subtitle: "User Testing",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "Throughout the development process, testing was conducted to ensure the functionality and usability of the AR experience. Feedback from testing sessions was used to iterate and refine the experience, addressing any issues or challenges encountered.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
  },
  {
    article_header: "Final Output",
    article_image: "/images/pawpatrol/merchandise.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "The final output is an immersive AR experience for CatGy Furn, accessible to users via a QR code trigger. Users can scan the QR code to launch the AR installation, where they can visualize and interact with 3D furniture pieces in their own space. The color palette chosen for the furniture pieces enhances the modern and high-quality aesthetic, providing users with a realistic and engaging shopping experience. This AR experience offers convenience and accessibility to users, allowing them to explore and customize furniture options from the comfort of their homes.This project demonstrates the power of AR technology in creating unique and engaging experiences, particularly in the realm of marketing and virtual shopping. By leveraging advanced multimedia technology, CatGy Furn's AR experience sets a new standard for online furniture shopping, offering users a seamless and immersive shopping journey.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
  },
];

export default { Content, Intro, Tools };
