const Intro =
  "For this project, I had to create a logo for an emerging entrepreneur within the renewable energy sector. Our main objective was to promote sustainability and environmental consciousness in a world powered by diverse natural resources. <br><br>I designed a moodboard that captured the essence of growth, sustainability, and professionalism using a colour palette made of green, yellow and blue.  Green representing eco-friendliness and growth, while  blue focuses on stability and trustworthiness. For typography, I opted for a Cherif Variable Regular font for its modern elegance and readability across platforms. I have selected  images of nature, green energy to reflect Green Thermique's values and vision.";

const Tools = ["Adobe Illustrator", "Adobe After Effects"];

const Content = [
  {
    article_header: "Ideation",
    article_leading_content: [
      "During our brainstorming phase, we wanted to craft an image that would resonate deeply with our audience. We knew that to convey the message of eco-friendliness effectively, our logo needed to be impactful and visually striking. That's why we explored various design options, ultimately settling on three logo variations that captured the interconnectedness between green energy and everyday life.",
    ],
    article_figures: [
      {
        link: "javascript:void(0)",
        img: "/images/greenthermique/idea1.jpg",
        alt: "Greenthermique logo Idea 1",
        caption: "",
        title: "Logo Idea 1",
        text: "",
        hasCopyright: true,
        tributes: {
          link: "https://www.freepik.com/free-vector/smart-home-technology-set-icons_4965965.htm",
          text: "Image by studiogstock on Freepik",
        },
      },
      {
        link: "javascript:void(0)",
        img: "/images/greenthermique/idea2.jpg",
        alt: "Greenthermique logo Idea 2",
        caption: "",
        title: "Logo Idea 2",
        text: "",
        hasCopyright: true,
        tributes: {
          link: "http://www.freepik.com",
          text: "Designed by Freepik",
        },
      },
      {
        link: "javascript:void(0)",
        img: "/images/greenthermique/idea3.jpg",
        alt: "Greenthermique logo Idea 3",
        caption: "",
        title: "Logo Idea 3",
        text: "",
        hasCopyright: true,
        tributes: {
          link: "https://www.freepik.com/free-vector/set-three-banners-with-renewable-energies_1048817.htm",
          text: "Image by macrovector on Freepik",
        },
      },
    ],
    subtitle: "Research and Inspiration",
    hasTitle: true,
    hasSubtitle: true,
    hasFigure: true,
    article_content: "",
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Style frame by CatGy",
  },
  {
    article_header: "",
    article_leading_content: [""],
    article_figures: [
      {
        link: "javascript:void(0)",
        img: "/images/greenthermique/LOGO1@4x.png",
        alt: "Greenthermique logo 1",
        caption: "",
        title: "Logo 1",
        text: "",
        modal_id: "gt1",
        isModal: true,
      },
      {
        link: "javascript:void(0)",
        img: "/images/greenthermique/LOGO2@4x.png",
        alt: "Greenthermique logo 2",
        caption: "",
        title: "Logo 2",
        text: "",
        modal_id: "gt2",
        isModal: true,
      },
      {
        link: "javascript:void(0)",
        img: "/images/greenthermique/LOGO3@4x.png",
        alt: "Greenthermique logo 3",
        caption: "",
        title: "Logo 3",
        text: "",
        modal_id: "gt3",
        isModal: true,
      },
    ],
    subtitle: "Logo concept",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: true,
    article_content:
      "The logos (1 and 2) captured the business's interest, prompting them to visualize the logo animations of both designs to decide which one would best represent their business. Both logos depict the connection between green energy and everyday life, incorporating elements such as homes, landscapes, solar panels, and appliances. The design and color scheme of each effectively communicate the business's core values and purpose, while also symbolizing how an energy-efficient environment represents sustainable energy sources.",
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Style frame by CatGy",
  },
  {
    article_header: "",
    article_leading_content: [
      "When presenting these options to the owner of Green Thermique, it became evident that logo variation 1 stood out as the most fitting choice.",
    ],
    article_figures: [
      {
        link: "javascript:void(0)",
        img: "/images/greenthermique/LOGO1@4x.png",
        alt: "Greenthermique logo 1",
        caption: "Gradient Logo<br>Click for more details",
        captionList: [
          "'Gradient colours offer a modern and dynamic look, add depth and dimension, reflect a unique brand personality, emphasize visual interest, and enhance the overall user experience on digital platforms.'",
        ],
        title: "Logo variation 1",
        text: "",
        modal_id: "gtv1",
        isModal: true,
      },
      {
        link: "javascript:void(0)",
        img: "/images/greenthermique/GT SOLID@4x.png",
        alt: "Greenthermique logo 2",
        caption: "Solid logo<br>Click for more details",
        captionList: [
          "'Solid colours are often associated with timelessness and simplicity. They add scalability, versatility, visibility  across mediums. Overall they convey a sense of readability and set an easy and memorable brand recognition overtime.'",
        ],
        title: "Logo variation 2",
        text: "",
        modal_id: "gtv2",
        isModal: true,
      },
    ],
    subtitle: "Logo style frame",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: true,
    article_content:
      "Green Thermique decision to choose the gradient logo over the solid version was driven by their desire to create a brand identity that not only reflects their values and aspirations but also resonates deeply with their audience. With its modern look, depth, and visual interest, the gradient logo embodies the spirit of innovation and sustainability that defines Green Thermique. Ultimately, the business opted for the Logo1 (Gradient logo) design and animation as it best aligns with their brand identity.",
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Style frame by CatGy",
  },
  {
    article_header: "",
    article_leading_content: [
      "When presenting these options to the owner of Green Thermique, it became evident that logo variation 1 stood out as the most fitting choice.",
    ],
    article_figures: [
      {
        link: "javascript:void(0)",
        img: "/images/greenthermique/businesscard1.png",
        alt: "Green Thermique Business card front face",
        caption: "Click for more details",
        captionList: [
          "'Front card. The designs has two tones of green, dark and light that creates an eye-catching and harmonious visual. The company logo stands proudly, symbolizing its commitment to eco-friendly practices. The name of the owner, direct phone number, email, and website is listed on the right side.'",
        ],
        title: "Business front card",
        text: "",
        modal_id: "gtv1",
        isModal: true,
      },
      {
        link: "javascript:void(0)",
        img: "/images/greenthermique/businesscard2.png",
        alt: "Green Thermique Business card back face",
        caption: "Click for more details",
        captionList: [
          "'Back Card, similar design with a QR code to visit Green Thermique&#146;s website. The front desk number, physical address and email is listed. This business card makes it easy to get in touch and shows Green Thermique&#146;s dedication to being green and easy to work with.'",
        ],
        title: "Business back card",
        text: "",
        modal_id: "gtv2",
        isModal: true,
      },
    ],
    subtitle: "Branding materials",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: true,
    article_content:
      "Green Thermique decision to choose the gradient logo over the solid version was driven by their desire to create a brand identity that not only reflects their values and aspirations but also resonates deeply with their audience. With its modern look, depth, and visual interest, the gradient logo embodies the spirit of innovation and sustainability that defines Green Thermique. Ultimately, the business opted for the Logo1 (Gradient logo) design and animation as it best aligns with their brand identity.",
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Style frame by CatGy",
  },
  {
    article_header: "",
    article_figures: [
      {
        link: "javascript:void(0)",
        img: "/images/greenthermique/storyboard.jpg",
        alt: "Green Thermique Storyboard",
        caption: "Click for more details",
        captionList: [
          "'Storyboard by CatGy for Green Thermique. The storyboard is a visual representation of the logo animation. It shows the sequence of the logo elements coming together to form the brand logo. The logo elements are the sun, leaves, roof, solar panel, and energy icons. The logo is formed and composed of the sun, roof, solar panel, leaves windows with environment sources icons ( wind, water, fire, ice). The business name starts appearing in form of type effect starting from the left to right side of the screen above the house and sun. The brand name continues to reveal its full name. All logo elements are fully displayed representing the brand focus on eco-friendliness.'",
        ],
        title: "Green Thermique Storyboard",
        fullScreen: true,
        text: "",
        modal_id: "gtst1",
        isModal: true,
      },
    ],
    subtitle: "Storyboard",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: true,
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Storyboard by CatGy",
  },
  {
    article_header: "Exploration",
    hasVideo: true,
    vidsrc: "https://www.youtube.com/embed/2ZHehrLd2Sg?si=pDRq7MTc3eOMRZtj",
    ismp4: true,
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    hasFigure: false,
    article_content: ["Exploration of logo 2 animation."],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
  },
];

export default { Content, Intro, Tools };
