const Intro =
  'The goal of this project was to develop the "Helpo" routine application, designed to immerse children in interactive and educational adventures centred around daily routines. With a focus on promoting self-regulation and understanding the importance of routines, the app aimed to empower children to become more independent and proactive in their daily activities.<br>Through a combination of engaging animations and user-friendly design, the app provided children with a fun and educational experience while simplifying parenting tasks for caregivers.';
const Tools = [
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adbobe XD",
  "Adobe After Effects",
];
const Content = [
  {
    article_header: "Ideation Process",
    article_image: "",
    article_img_alt: "",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [""],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: false,
    link_name: "Image by starline",
  },
  {
    article_header: "",
    article_image: "",
    article_img_alt: "",
    subtitle: "Storyboard and Script",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "The project began with extensive planning and research to develop a storyboard and script that effectively communicated the importance of daily routines to children. I got ideas from other kids' apps and talked to my own kids to make sure the story was interesting and easy to understand",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: false,
    link_name: "Image by starline",
  },
  {
    article_header: "",
    article_image: "",
    article_img_alt: "",
    subtitle: "Preparation material",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "I prepared the necessary materials for the app's development which will mainly be delivered via UI UX designs. I used different tools and technology to make graphics, animations, and sounds for the app like LeonardoAI, Adobe Photoshop, Illustrator, and Premiere Pro.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: false,
    link_name: "Image by starline",
  },
  {
    article_header: "",
    article_image: "",
    article_img_alt: "",
    subtitle: "Shots/ Screens for the interview",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "Screenshots of the app's colourful interface and engaging animations. Different Images showcasing the app's characters and interactive features.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: false,
    link_name: "Image by starline",
  },
  {
    article_header: "User Testing",
    article_image: "",
    article_img_alt: "",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Each testing session began with a brief introduction to the app's purpose and features, followed by guided interaction with the prototype.<br>To ensure the effectiveness and user-friendliness of the Helpo app prototype, user testings were conducted across the morning routine scenario, which is set up by the parent based on their routine preferences. Participants were invited to interact with the app and provide feedback on the Helpo app's usability, functionality, and potential impact on children's daily routines.<br>Feedback from participants were used to refine the app's design and features, ensuring that it meets the needs and preferences of its target audience effectively",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: false,
    link_name: "Image by starline",
  },
  {
    article_header: "Final Output",
    article_image: "",
    article_img_alt: "",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      'This project was mainly designed using a new feature introduced by Adobe during their 2023 Annual Conference. While exploring the new Al generative adobe tool features I begin creating images, environment scenes and a logo to my liking for my project "HELPO" Daily Routine. The integration of AI tools and Adobe software have definitely facilitated the creative processor Helpo.<br>While there are still skills to develop and refinements to make, I\'m satisfied with the effort and ideas shared, hopeful that Helpo will provide a user-friendly and engaging experience for children and families alike.',
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: false,
    link_name: "Image by starline",
  },
];

export default { Content, Intro, Tools };
