const Intro =
  "For this project, I had the privilege of interviewing Meredith, the owner of “Julimay Grocery Store”  in York, ON. Meredith graciously shared her journey as a new successful entrepreneur amidst the challenges of the COVID-19 pandemic. I oversaw all aspects of the project, from scriptwriting to final editing, with the goal of capturing Meredith’s story in a genuine and inspiring way.";
const Tools = ["Adobe Photoshop", "Adobe Audition", "Adobe Premiere Pro"];
const Content = [
  {
    article_header: "Ideation",
    article_image: "/images/helpo/paw-patrol-logo.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Throughout this interview, the owner of the store explained the challenges she faced while opening her store in 2022 during the Covid-19 pandemic and also shared pieces of advices for success.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Style frame by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/pawpatrol/todo.png",
    article_img_alt: "Article image",
    subtitle: "Script",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "For the script, I included questions covering her motivations for opening the store, challenges faced during the startup process, experiences as a female entrepreneur, industry pros and cons, advice for aspiring business owners, feedback on her journey, and future aspirations. The answers to the following question help in providing a comprehensive framework for the interview, ensuring that key aspects of Meredith's story were explored.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Storyboard by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/pawpatrol/merchandise.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Why did you choose to open a grocery store? <br>Hints: Hubbies, skills, influences, factors that contributed to your final decision.",
      "What challenges did you face during the start up process? <br>Hints: Covid 19 pandemic, Business registration / legal procedures, cost, strategic plan...",
      "What is it like to be a female entrepreneur?<br>Hints: Struggles faced while working with other third parties (suppliers, government entities, customer...)",
      "What are the Pro's and Con's in this specific industry?<br>Hints: What works well? What requires more support?",
      "What advice would you give to those who would like to start a business?<br>Hints: Is it difficult to run a business? What to expect? What are your top 3 pieces of advice for success?",
      "What's your feedback now that you have established your business?<br>Hints: Do you feel satisfied? Were you able to meet your expectations? What's you feel is missing?",
      "Where do you see yourself or your business within the next 5 to 10 years?<br>Hints: Remain a small to midsize business? New business ventures, international expansion?",
    ],
    isContentList: true,
    isNumberedList: true,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: false,
    link_name: "Image by starline",
  },
  {
    article_header: "",
    article_image: "/images/pawpatrol/merchandise.png",
    article_img_alt: "Article image",
    subtitle: "Storyboard",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "This next step goal was to developed a detailed storyboard to visualize the interview's structure and flow. It outlined the sequence of shots, camera angles, and transitions to capture Meredith's journey effectively. Additionally, the storyboard incorporated B-rolls showcasing Meredith's daily operations at the grocery store. This visual roadmap guided the filming process and ensured cohesive storytelling.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: false,
    link_name: "Image by starline",
  },
  {
    article_header: "Preparation materials",
    article_image: "",
    article_img_alt: "",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Prior to the interview, I had to prepare to ensure an average optimal filming conditions. Equipment setup, including cameras, microphones, and lighting, was arranged to achieve high-quality audio and visual output. Additionally, interview prompts and cues were prepared to facilitate engaging and informative conversations with Meredith. We made sure everything was ready to go.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: false,
    link_name: "Image by starline",
  },
  {
    article_header: "",
    article_image: "",
    article_img_alt: "",
    subtitle: "Shots/ Screens for the interview",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "Throughout the interview, a variety of shots were captured to visually enhance Meredith's story. Close-up shots showcased her emotions and expressions, while wide shots captured the ambiance of the grocery store environment. B-roll footage provided supplementary visuals of Meredith's daily activities, offering viewers a comprehensive glimpse into her entrepreneurial journey.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: false,
    link_name: "Image by starline",
  },
  {
    article_header: "Final Output",
    article_image: "",
    article_img_alt: "",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "The final edited interview video seamlessly integrated Meredith's inspiring journey with captivating visuals and audio elements. Adobe Audition was utilized for audio editing of the voiceovers by Meredith and myself, along with background music to enhance the storytelling experience. The video editing process via Adobe Premiere Pro involved selection of footage, precise timing of transitions, and incorporation of visual effects to maintain viewer engagement. The result was a compelling narrative that resonated with audiences, showcasing Meredith's resilience, wisdom, and entrepreneurial spirit amidst adversity.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: false,
    link_name: "Image by starline",
  },
];
export default { Content, Intro, Tools };
