const Intro =
  "For this project, I worked on a \"Branding package\", creating a logo, branding, and website prototype for a new restaurant called CaribFood. I chose the name CaribFood because it's short and easy to remember. The tagline, 'Discover the Caribbean flavour', and the bright colours match the idea of tropical elegance.";
const Tools = ["Adobe Illustrator", "Adobe Photoshop", "Adobe XD"];
const Content = [
  {
    article_header: "Ideation",
    article_image: "/images/caribfood/caribfood_4.png",
    article_img_alt: "Article image",
    subtitle: "Logo",
    hasTitle: true,
    hasSubtitle: true,
    hasFigure: false,
    article_content:
      "To get the right look and feel, I made two mood-boards: one called 'Frenzy' and the other 'Chic.' I used words like fresh, tasty, vibrant, and friendly to guide my design choices. The colours I picked—yellow and green—show the liveliness of the Caribbean.",
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "CaribFood logo by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/Branding.png",
    article_img_alt: "Article image",
    subtitle: "Branding",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "Typography was really important. We picked clean and modern fonts like Bodoni 72 and Helvetica Light for their readability and contemporary appeal. The design has curved shapes and sleek lines to make it feel warm and stylish.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: true,
    article_img_caption: "Storyboard by CatGy",
    extraImages: [
      {
        link: "",
        img: "/images/caribfood/gallery/caribfood_1_test.png",
        alt: "portfolio image 1",
        caption: "Tools: Adobe Illustrator",
        title: "",
        text: "",
      },
      {
        link: "",
        img: "/images/caribfood/gallery/caribfood_2_test.png",
        alt: "portfolio image 1",
        caption: "Tools: Adobe Illustrator",
        title: "",
        text: "",
      },
      {
        link: "",
        img: "/images/caribfood/gallery/Home-test.png",
        alt: "portfolio image 1",
        caption: "Tools: Adobe Illustrator",
        title: "",
        text: "",
      },
      {
        link: "",
        img: "/images/caribfood/gallery/caribfood-mobile-4-test.png",
        alt: "portfolio image 1",
        caption: "Tools: Adobe Illustrator",
        title: "",
        text: "",
      },
    ],
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "CaribFood targets a diverse demographic, including families, friends, and culinary enthusiasts eager to explore Caribbean cuisine. This diversity was reflected in the user testing phase, where a varied group of users, including peers, friends, and family, engaged with the prototype website, to make sure it's easy to use.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "The branding collateral for this project includes the following essential items:",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Business card: The business card showcases the logo along with the restaurant's contact information and a barcode, all while maintaining a sleek and modern aesthetic. ",
      "Letterhead: The letterhead maintains the colour scheme and presents a professional and cohesive appearance, ideal for official documents and correspondence",
      "Envelope: The standard envelope reflects the branding elements, featuring a harmonious colour scheme that embodies the essence of the restaurant's identity.",
    ],
    isContentList: true,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Together, these collateral pieces contribute to a consistent and memorable brand image for CaribFood Restaurant Prototype.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "Wireframe to high fidelity prototypes",
    hasTitle: false,
    hasSubtitle: true,
    hasFigure: false,
    article_content: [
      "For the CaribFood prototype, I started by drawing basic layout and structure of the application across different screen sizes, focusing on key functionalities such as menu browsing, ordering, and checkout.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "I then progressively developed low and mid-fidelity designs by introduced more detailed visual elements, including colour schemes, typography, and imagery, to enhance the user experience further. The mobile version prioritized streamlined navigation and intuitive touch controls, while the tablet and desktop versions showcased rich visuals and enhance user engagement.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "User Testing",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "To assess the user experience of CaribFood's prototype and ensure it matches the brand's identity while catering to a diverse audience, we conducted the following user testing:We invited a varied group, including peers, friends, family members, and food enthusiasts, to interact with the UI/UX prototype of the CaribFood website. Participants were asked to place an order for a complete meal, consisting of a Creole Bliss meal and a Carib Smoothie, and proceed to payment to obtain a receipt via this link:",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
    hasLink: true,
    link_name: "CaribFood Restaurant",
    article_link_text: "CaribFood Restaurant",
    article_link:
      "https://xd.adobe.com/view/80c1462a-d598-4cb6-b291-544383abd601-d592/",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "The testing scenario assumed participants had already created an account or used an authentication method (such as Google) to sign up. They were then prompted to follow the provided scenario for placing their order.We assessed various metrics during the testing process:",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Exploration and Navigation: Participants were instructed to explore different sections of the website or app to find information about the restaurant, menu offerings, and contact details.",
      "Placing an Order: Participants were asked to simulate the process of ordering a meal through the prototype to evaluate the ease of use and clarity of the ordering system.",
      "Finding Information: Participants were tasked with locating specific information, such as the restaurant's address, operating hours, and detailed menu options, including vegetarian or gluten-free choices.",
      "Contact and Support: Participants were requested to locate the contact information and simulate sending a query or feedback to assess the accessibility of customer support.",
    ],
    isContentList: true,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: false,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Feedback was collected to evaluate navigation, ordering, information retrieval, and support features. Metrics such as task success, time-on-task, satisfaction, accessibility, design aesthetics, and responsiveness were measured.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
  {
    article_header: "Final Ouput",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    hasFigure: false,
    article_content: [
      "Overall, the goal of this user testing was to refine the platform, ensuring it offers a user-friendly and visually appealing experience that captures the essence of the Caribbean spirit while meeting the diverse needs of its users.",
    ],
    isContentList: false,
    isNumberedList: false,
    hasMoreImages: false,
    article_img_caption: "High Fidelity design by CatGy",
  },
];

module.exports = { Content, Intro, Tools };
