/**
 * Greenthermique page data :
 */
const GreenthermiquePortfolioArticles = [
  {
    article_header: "Ideation",
    article_image: "/images/greenthermique/gt_style_frames.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content:
      "I was tasked by my friend, who's launching a green energy business, to craft a logo that conveys a swift and unmistakable message about the promise of sustainable, eco-friendly power. With green energy stemming from diverse natural sources like solar, wind, geothermal, and more, the wealth of information can overwhelm those with busy schedules. My challenge was twofold: how to distill this array of ideas into a single, impactful image, and how to ensure its resonance with the intended audience. My journey began with in-depth research into contemporary green energy concepts, leveraging brainstorming sessions with friends and online resources to refine my ideas. Combining feasible suggestions and feedback, I used Adobe Illustrator to craft visuals and a storyboard, laying the foundation for the logo's design process and subsequent animation. This animated logo's storyboard is as follows: [details to be added].",
    isContentList: false,
    hasMoreImages: false,
    article_img_caption: "Style frame by CatGy",
  },
  {
    article_header: "Storyboard",
    article_image: "/images/greenthermique/gt_storyboard.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      "Scene 1: The animation begins with a soothing audio, a blue sky, and a gentle sunrise, using a slow ease-in technique for a serene start. ",
      "Scene 2: As the sun shines brightly, house pieces gradually emerge from the screen's lower sides, slowly assembling the house at a regular pace.",
      "Scene 3: The house is fully constructed as the sun rises slowly above its roof.",
      "Scene 4: Numerous colorful glass pieces simulate a snowfall effect as they appear from the upper screen, converging to create a single window on the house's wall.",
      "Scene 5: Solar panel components slide in from the bottom, ascend to the roof, and fix themselves in place.",
      "Scene 6: Green arrows symbolizing renewable energy production enter from the sides, circling the home.",
      "Scene 7: Falling leaves from above unite to form one leaf, while the company's name appears in the center.",
      "Scene 8: The leaf lands on the 'I' in the company name, emphasizing the business identity. ",
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Storyboard by CatGy",
  },
  {
    article_header: "Final output",
    article_image: "/images/greenthermique/gt_logo_3.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content:
      "The business owner decided to go with another variation of the logo. The final logo illustrate the connection between green energy and everyday life, featuring elements like homes, landscapes, solar panels, and appliances. The first image combines various aspects of an energy-efficient environment, while the second emphasizes hydro energy's importance in daily living. The third image symbolizes the sources of green energy, showing it originates from the surrounding environment, such as natural resources, sunlight, wind, or water.",
    isContentList: false,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
  },
];

/**
 * CaribFood page data
 */
const CaribfoodPortfolioArticles = [
  {
    article_header: "Ideation",
    article_image: "/images/caribfood/caribfood_4.png",
    article_img_alt: "Article image",
    subtitle: "Logo",
    hasTitle: true,
    hasSubtitle: true,
    article_content:
      "As we embark on our mission to introduce the delectable world of fresh Caribbean cuisine to a global audience, we've carefully selected the unforgettable moniker, 'CaribFood.' Opting for a short and simple name holds several advantages like enhancing memorability, ensuring effortless pronunciation, and providing clarity to our brand's identity and values. The logo, thoughtfully designed with a bold yellow backdrop, is intentionally designed to captivate attention.  It marries simplicity with memorability, featuring a palm tree that exudes the vibrant essence of the Caribbean, alongside a tantalizing sandwich that is sure to pique your appetite. 'CaribFood' is more than just a name; it's an open invitation to savor the culinary delights of the Caribbean.",
    isContentList: false,
    hasMoreImages: false,
    article_img_caption: "CaribFood logo by CatGy",
  },
  {
    article_header: "",
    article_image: "/images/caribfood/Branding.png",
    article_img_alt: "Article image",
    subtitle: "Branding",
    hasTitle: false,
    hasSubtitle: true,
    article_content: [
      'For this project, I created two variations of moodboards,  "Frenzy Moodboard" and  "Chic Moodboard"  to create a visually captivating and tropical feel.',
      "Keywords: Fresh, tasty, vibrant, friendly",
      'Concept: "Tropical Elegance"',
      "Tagline: Discover the Caribbean flavour",
      "Color Palette: ",
      {
        isColorPalette: true,
        colors: [
          {
            color: "#F1C90F",
            color_text:
              "Primary Color: Vibrant Yellow - Energetic and sunny, evoking the lively and joyful atmosphere of the Caribbean.",
          },
          {
            color: "#094231",
            color_text:
              "Secondary Color: Rich Green - Represents the lush landscapes and fresh ingredients of the region.",
          },
        ],
      },
      "Design Elements: The design elements incorporate round and curved shapes, creating a welcoming and organic feel, reminiscent of the gentle waves and tropical scenery. Use sleek, modern lines and shapes to convey sophistication and style.",
      "Typography:",
      "Typeface: A modern and clean font for a cool and friendly look with easy readability.",
      "Heading: Bodoni 72, Regular, Book",
      "Subheading: Noteworthy Light, Bold",
      "Body font: Helvetica Light, Bold, regular",
      "Visuals: Visuals in the branding package include imagery of exotic Caribbean landscapes, tantalizing food, and vibrant cultural scenes, capturing the essence of the region and the restaurant's offerings.",
      "Audience: CaribFood caters to a diverse audience like families, friends and any enthusiasts looking for a taste of the  delicious Caribbean cuisine.",
      "Branding Collateral: Business Card: Features the logo, the restaurant's contact information and barcode maintaining a modern aesthetic.",
      "Letterhead: Maintains the color scheme and a professional and cohesive look, perfect for official documents and correspondence.",
      "Standard Envelope: The envelope design echoes the branding elements with a color scheme and that represents the restaurant's identity.",
    ],
    isContentList: true,
    hasMoreImages: true,
    article_img_caption: "Storyboard by CatGy",
    extraImages: [
      {
        link: "",
        img: "/images/caribfood/gallery/caribfood_1_test.png",
        alt: "portfolio image 1",
        caption: "Tools: Adobe Illustrator",
        title: "",
        text: "",
      },
      {
        link: "",
        img: "/images/caribfood/gallery/caribfood_2_test.png",
        alt: "portfolio image 1",
        caption: "Tools: Adobe Illustrator",
        title: "",
        text: "",
      },
      {
        link: "",
        img: "/images/caribfood/gallery/Home-test.png",
        alt: "portfolio image 1",
        caption: "Tools: Adobe Illustrator",
        title: "",
        text: "",
      },
      {
        link: "",
        img: "/images/caribfood/gallery/caribfood-mobile-4-test.png",
        alt: "portfolio image 1",
        caption: "Tools: Adobe Illustrator",
        title: "",
        text: "",
      },
    ],
  },
  {
    article_header: "User Testing",
    article_image: "/images/caribfood/caribfood_7.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      "To evaluate the user experience of CaribFood's prototye to ensure it aligns with the brand's identity and caters to a diverse audience i have conducted a user testing as follow:",
      "Invited a diverse group of users, peers, friends and families including food enthusiasts.",
      "Scenario: The participants interact with a UI/UX prototype of the CaribFood website to order a complete meal including a meal and drink then pay and obtain a receipt.",
      "Reviews metrics to evaluate: Exploration and Navigation: Ask participants to explore the prototype, navigate through different sections of the website or app, and find information about the restaurant, menu, and contact details.",
      "Placing an Order: Instruct participants to simulate the process of placing an order for a meal through the prototype. This will assess the ease of use and clarity of the ordering system.",
      "Finding Information: Ask participants to find specific information, such as the restaurant's address, hours of operation, and a detailed menu for a specific dietary preference (e.g., vegetarian or gluten-free options).",
      "Contact and Support: Request participants to locate the contact information and simulate sending a query or feedback to assess the accessibility of customer support.",
      "Collect feedback on : Evaluate navigation, ordering, information retrieval, and support features.Metrics: Measure task success, time-on-task, satisfaction, accessibility, design aesthetics, and responsiveness.",
      "This user testing aimed to refine the platform, providing a user-friendly and visually appealing experience that embodies the Caribbean spirit, meeting the needs of various users.",
    ],
    hasLink: true,
    article_link:
      "https://xd.adobe.com/view/80c1462a-d598-4cb6-b291-544383abd601-d592/",
    article_link_text: "High Fidelity Link",
    isContentList: true,
    article_img_caption: "High Fidelity design by CatGy",
  },
];

/**
 * Julimay Grocery shop page data
 */
const PawpatrolArticles = [
  {
    article_header: "Ideation Process",
    article_image: "/images/pawpatrol/paw-patrol-logo.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      "To complete the above AR experience prototype, I proceeded as follow:",
      'Re-created the vectorized version of the "Paw Patrol" logo using Adobe Illustrator.',
      "Create 2 versions of vectors (Solid vs. gradient) using a vibrant and colorful palette of the logo theme (red, yellow, blue).",
      "Opted for gradient colors logo to animate for a unique and eye-catching appearance logo.",
      'Used a "3D and material" effect to convert the logo vector layers to a 3D format.',
      "Exported the vectors using the GLTF format into Adobe Substance 3D Stager optimization purposes.",
      'Used Adobe Audition to record my enthusiastic children voice overs of their favourite "Paw Patrol" tv-show to add a personal and cute touch to the project',
      "Imported all created assets (Images, audio) into a new Adobe Aero project file to create AR animation and interactions to engage the audience.",
      "Show my prototype to others for feedback and improvement for a better user experience for the viewers.",
      "Made video production using records, audio, effects using Premiere Pro to showcase my AR prototype.",
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Style frame by CatGy",
  },
  {
    article_header: "Storyboard",
    article_image: "/images/pawpatrol/storyboard.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      "Scene 1: Anthem background sound. Paw Patrol emblem (shield) is on a clean background.",
      'Scene 2: The letter "P" of "Paw" fades in.',
      'Scene 3: The letter "A" of "Paw" fades in next to the letter "P".',
      'Scene 4: The letter "W" of "Paw" fades in next to the "P" and "A" forming the word "PAW".',
      "Scene 5: The bone fades in through the shield (Layer 1: white) and (Layer 2: blue) and (Layer 3 white).",
      "Scene 6: The 3 bones (white, blue,white) bounce respectively top to bottom.",
      'Scene 7: The word "Patrol" fades in ahead of the layer3: white bone in front of the shield.',
      'Scene 8: The far back layers (layer1: white ) spin in one direction while "Patrol" remains displayed.',
      'Scene 9:  The middle back layers (layer2: blue) spin in the opposite direction, while "Patrol" remains displayed.',
      "Scene 10: All assets (paw, letters, bones) except the shield spread, dissolve and disappear in different directions prompting the audience's curiosity.",
      'Scene 11: Voice over calling for action. Tap the shield for the catchphrase voice over & "Rubble" pup badge to fade in & bounce fade out. ',
      'Scene 12: Tap the shield.  Catchphrase / voice over. "Marshall" pup badge to display, rotate and fade out.',
      'Scene 13: Tap.Catchphrase / voice over. For the "Chase" pup badge to appear. Zoom out, zoom in then fade out.',
      'Scene 14: Tap. Catchphrase / voice over. For the "Sky" pup badge to appear slide to the right then fade out.',
      'Scene 15: Tap. Catchphrase / voice over. For the "Zuma" pup badge to appear. Spin then fade out',
      'Scene 16: Voice over. The animation ends with the "Dog Paw" on the shield as a way to say bye marking the successful rescue mission',
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Storyboard by CatGy",
  },
  {
    article_header: "Promotional Assets",
    article_image: "/images/pawpatrol/merchandise.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      'Logo Animation Video: Create a captivating video showcasing the logo animation concept. Highlight the fading letters, the bone layers, the dynamic "Patrol," and the interactive shield.',
      "Printed Posters: Design posters with a still frame of the logo animation and details about where and how to access it.",
      "Website Banner: Update the Paw Patrol website with an engaging banner that invites users to tap on the shield to discover the pups' team. ",
      "Mobile App : Paw Patrol game/ activity app to attract users to the interactive logo experience.",
      "Merchandise: Notebook, mugs, business card, letter, envelope, pen/ pencils, shopping bag, phone case etc.",
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: true,
    link_name: "Image by starline",
  },
];

const HelpoArticles = [
  {
    article_header: "Ideation Process",
    article_image: "/images/helpo/paw-patrol-logo.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      "To complete the above AR experience prototype, I proceeded as follow:",
      'Re-created the vectorized version of the "Paw Patrol" logo using Adobe Illustrator.',
      "Create 2 versions of vectors (Solid vs. gradient) using a vibrant and colorful palette of the logo theme (red, yellow, blue).",
      "Opted for gradient colors logo to animate for a unique and eye-catching appearance logo.",
      'Used a "3D and material" effect to convert the logo vector layers to a 3D format.',
      "Exported the vectors using the GLTF format into Adobe Substance 3D Stager optimization purposes.",
      'Used Adobe Audition to record my enthusiastic children voice overs of their favourite "Paw Patrol" tv-show to add a personal and cute touch to the project',
      "Imported all created assets (Images, audio) into a new Adobe Aero project file to create AR animation and interactions to engage the audience.",
      "Show my prototype to others for feedback and improvement for a better user experience for the viewers.",
      "Made video production using records, audio, effects using Premiere Pro to showcase my AR prototype.",
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Style frame by CatGy",
  },
  {
    article_header: "Storyboard",
    article_image: "/images/pawpatrol/storyboard.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      "Scene 1: Anthem background sound. Paw Patrol emblem (shield) is on a clean background.",
      'Scene 2: The letter "P" of "Paw" fades in.',
      'Scene 3: The letter "A" of "Paw" fades in next to the letter "P".',
      'Scene 4: The letter "W" of "Paw" fades in next to the "P" and "A" forming the word "PAW".',
      "Scene 5: The bone fades in through the shield (Layer 1: white) and (Layer 2: blue) and (Layer 3 white).",
      "Scene 6: The 3 bones (white, blue,white) bounce respectively top to bottom.",
      'Scene 7: The word "Patrol" fades in ahead of the layer3: white bone in front of the shield.',
      'Scene 8: The far back layers (layer1: white ) spin in one direction while "Patrol" remains displayed.',
      'Scene 9:  The middle back layers (layer2: blue) spin in the opposite direction, while "Patrol" remains displayed.',
      "Scene 10: All assets (paw, letters, bones) except the shield spread, dissolve and disappear in different directions prompting the audience's curiosity.",
      'Scene 11: Voice over calling for action. Tap the shield for the catchphrase voice over & "Rubble" pup badge to fade in & bounce fade out. ',
      'Scene 12: Tap the shield.  Catchphrase / voice over. "Marshall" pup badge to display, rotate and fade out.',
      'Scene 13: Tap.Catchphrase / voice over. For the "Chase" pup badge to appear. Zoom out, zoom in then fade out.',
      'Scene 14: Tap. Catchphrase / voice over. For the "Sky" pup badge to appear slide to the right then fade out.',
      'Scene 15: Tap. Catchphrase / voice over. For the "Zuma" pup badge to appear. Spin then fade out',
      'Scene 16: Voice over. The animation ends with the "Dog Paw" on the shield as a way to say bye marking the successful rescue mission',
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Storyboard by CatGy",
  },
  {
    article_header: "Promotional Assets",
    article_image: "/images/pawpatrol/merchandise.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      'Logo Animation Video: Create a captivating video showcasing the logo animation concept. Highlight the fading letters, the bone layers, the dynamic "Patrol," and the interactive shield.',
      "Printed Posters: Design posters with a still frame of the logo animation and details about where and how to access it.",
      "Website Banner: Update the Paw Patrol website with an engaging banner that invites users to tap on the shield to discover the pups' team. ",
      "Mobile App : Paw Patrol game/ activity app to attract users to the interactive logo experience.",
      "Merchandise: Notebook, mugs, business card, letter, envelope, pen/ pencils, shopping bag, phone case etc.",
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: true,
    link_name: "Image by starline",
  },
];

const JulimayArticles = [
  {
    article_header: "Ideation Process",
    article_image: "/images/helpo/paw-patrol-logo.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      "To complete the above AR experience prototype, I proceeded as follow:",
      'Re-created the vectorized version of the "Paw Patrol" logo using Adobe Illustrator.',
      "Create 2 versions of vectors (Solid vs. gradient) using a vibrant and colorful palette of the logo theme (red, yellow, blue).",
      "Opted for gradient colors logo to animate for a unique and eye-catching appearance logo.",
      'Used a "3D and material" effect to convert the logo vector layers to a 3D format.',
      "Exported the vectors using the GLTF format into Adobe Substance 3D Stager optimization purposes.",
      'Used Adobe Audition to record my enthusiastic children voice overs of their favourite "Paw Patrol" tv-show to add a personal and cute touch to the project',
      "Imported all created assets (Images, audio) into a new Adobe Aero project file to create AR animation and interactions to engage the audience.",
      "Show my prototype to others for feedback and improvement for a better user experience for the viewers.",
      "Made video production using records, audio, effects using Premiere Pro to showcase my AR prototype.",
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Style frame by CatGy",
  },
  {
    article_header: "Storyboard",
    article_image: "/images/pawpatrol/storyboard.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      "Scene 1: Anthem background sound. Paw Patrol emblem (shield) is on a clean background.",
      'Scene 2: The letter "P" of "Paw" fades in.',
      'Scene 3: The letter "A" of "Paw" fades in next to the letter "P".',
      'Scene 4: The letter "W" of "Paw" fades in next to the "P" and "A" forming the word "PAW".',
      "Scene 5: The bone fades in through the shield (Layer 1: white) and (Layer 2: blue) and (Layer 3 white).",
      "Scene 6: The 3 bones (white, blue,white) bounce respectively top to bottom.",
      'Scene 7: The word "Patrol" fades in ahead of the layer3: white bone in front of the shield.',
      'Scene 8: The far back layers (layer1: white ) spin in one direction while "Patrol" remains displayed.',
      'Scene 9:  The middle back layers (layer2: blue) spin in the opposite direction, while "Patrol" remains displayed.',
      "Scene 10: All assets (paw, letters, bones) except the shield spread, dissolve and disappear in different directions prompting the audience's curiosity.",
      'Scene 11: Voice over calling for action. Tap the shield for the catchphrase voice over & "Rubble" pup badge to fade in & bounce fade out. ',
      'Scene 12: Tap the shield.  Catchphrase / voice over. "Marshall" pup badge to display, rotate and fade out.',
      'Scene 13: Tap.Catchphrase / voice over. For the "Chase" pup badge to appear. Zoom out, zoom in then fade out.',
      'Scene 14: Tap. Catchphrase / voice over. For the "Sky" pup badge to appear slide to the right then fade out.',
      'Scene 15: Tap. Catchphrase / voice over. For the "Zuma" pup badge to appear. Spin then fade out',
      'Scene 16: Voice over. The animation ends with the "Dog Paw" on the shield as a way to say bye marking the successful rescue mission',
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Storyboard by CatGy",
  },
  {
    article_header: "Promotional Assets",
    article_image: "/images/pawpatrol/merchandise.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      'Logo Animation Video: Create a captivating video showcasing the logo animation concept. Highlight the fading letters, the bone layers, the dynamic "Patrol," and the interactive shield.',
      "Printed Posters: Design posters with a still frame of the logo animation and details about where and how to access it.",
      "Website Banner: Update the Paw Patrol website with an engaging banner that invites users to tap on the shield to discover the pups' team. ",
      "Mobile App : Paw Patrol game/ activity app to attract users to the interactive logo experience.",
      "Merchandise: Notebook, mugs, business card, letter, envelope, pen/ pencils, shopping bag, phone case etc.",
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: true,
    link_name: "Image by starline",
  },
];

const FurnitureAppArticles = [
  {
    article_header: "Ideation Process",
    article_image: "/images/helpo/paw-patrol-logo.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      "To complete the above AR experience prototype, I proceeded as follow:",
      'Re-created the vectorized version of the "Paw Patrol" logo using Adobe Illustrator.',
      "Create 2 versions of vectors (Solid vs. gradient) using a vibrant and colorful palette of the logo theme (red, yellow, blue).",
      "Opted for gradient colors logo to animate for a unique and eye-catching appearance logo.",
      'Used a "3D and material" effect to convert the logo vector layers to a 3D format.',
      "Exported the vectors using the GLTF format into Adobe Substance 3D Stager optimization purposes.",
      'Used Adobe Audition to record my enthusiastic children voice overs of their favourite "Paw Patrol" tv-show to add a personal and cute touch to the project',
      "Imported all created assets (Images, audio) into a new Adobe Aero project file to create AR animation and interactions to engage the audience.",
      "Show my prototype to others for feedback and improvement for a better user experience for the viewers.",
      "Made video production using records, audio, effects using Premiere Pro to showcase my AR prototype.",
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Style frame by CatGy",
  },
  {
    article_header: "Storyboard",
    article_image: "/images/pawpatrol/storyboard.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      "Scene 1: Anthem background sound. Paw Patrol emblem (shield) is on a clean background.",
      'Scene 2: The letter "P" of "Paw" fades in.',
      'Scene 3: The letter "A" of "Paw" fades in next to the letter "P".',
      'Scene 4: The letter "W" of "Paw" fades in next to the "P" and "A" forming the word "PAW".',
      "Scene 5: The bone fades in through the shield (Layer 1: white) and (Layer 2: blue) and (Layer 3 white).",
      "Scene 6: The 3 bones (white, blue,white) bounce respectively top to bottom.",
      'Scene 7: The word "Patrol" fades in ahead of the layer3: white bone in front of the shield.',
      'Scene 8: The far back layers (layer1: white ) spin in one direction while "Patrol" remains displayed.',
      'Scene 9:  The middle back layers (layer2: blue) spin in the opposite direction, while "Patrol" remains displayed.',
      "Scene 10: All assets (paw, letters, bones) except the shield spread, dissolve and disappear in different directions prompting the audience's curiosity.",
      'Scene 11: Voice over calling for action. Tap the shield for the catchphrase voice over & "Rubble" pup badge to fade in & bounce fade out. ',
      'Scene 12: Tap the shield.  Catchphrase / voice over. "Marshall" pup badge to display, rotate and fade out.',
      'Scene 13: Tap.Catchphrase / voice over. For the "Chase" pup badge to appear. Zoom out, zoom in then fade out.',
      'Scene 14: Tap. Catchphrase / voice over. For the "Sky" pup badge to appear slide to the right then fade out.',
      'Scene 15: Tap. Catchphrase / voice over. For the "Zuma" pup badge to appear. Spin then fade out',
      'Scene 16: Voice over. The animation ends with the "Dog Paw" on the shield as a way to say bye marking the successful rescue mission',
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Storyboard by CatGy",
  },
  {
    article_header: "Promotional Assets",
    article_image: "/images/pawpatrol/merchandise.png",
    article_img_alt: "Article image",
    subtitle: "",
    hasTitle: true,
    hasSubtitle: false,
    article_content: [
      'Logo Animation Video: Create a captivating video showcasing the logo animation concept. Highlight the fading letters, the bone layers, the dynamic "Patrol," and the interactive shield.',
      "Printed Posters: Design posters with a still frame of the logo animation and details about where and how to access it.",
      "Website Banner: Update the Paw Patrol website with an engaging banner that invites users to tap on the shield to discover the pups' team. ",
      "Mobile App : Paw Patrol game/ activity app to attract users to the interactive logo experience.",
      "Merchandise: Notebook, mugs, business card, letter, envelope, pen/ pencils, shopping bag, phone case etc.",
    ],
    isContentList: true,
    hasMoreImages: false,
    article_img_caption: "Designed by CatGy",
    hasLink: true,
    link_name: "Image by starline",
  },
];

module.exports = {
  CaribfoodPortfolioArticles,
  GreenthermiquePortfolioArticles,
  PawpatrolArticles,
  HelpoArticles,
  JulimayArticles,
  FurnitureAppArticles,
};
