name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build and Export
        run: |
          node build.js

      - name: List files in dist
        run: ls -la ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist # Directory to deploy
          github_token: ${{ secrets.GITHUB_TOKEN }}
